[package]
name = "p10-voracious-code-storage"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
wasi.workspace = true
wasi-async-runtime.workspace = true
wasi-async.workspace = true
tracing.workspace = true
thiserror.workspace =  true

clap.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
