// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
// Options used:

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.24.0:p04-unusual-database-program:encoded world")]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 224] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07N\x01A\x02\x01A\0\x04\
\x01Ccomponent:p04-unusual-database-program/p04-unusual-database-program\x04\0\x0b\
\"\x01\0\x1cp04-unusual-database-program\x03\0\0\0G\x09producers\x01\x0cprocesse\
d-by\x02\x0dwit-component\x070.202.0\x10wit-bindgen-rust\x060.24.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
