// Generated by `wit-bindgen` 0.24.0. DO NOT EDIT!
// Options used:

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.24.0:p00-smoke-test:encoded world")]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 182] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x072\x01A\x02\x01A\0\x04\
\x01'component:p00-smoke-test/p00-smoke-test\x04\0\x0b\x14\x01\0\x0ep00-smoke-te\
st\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.202.0\x10\
wit-bindgen-rust\x060.24.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
