[package]
name = "wasi-async-runtime"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.component]
package = "component:wasi-async-runtime"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen-rt.workspace = true
wasi.workspace = true
slab.workspace = true
tracing.workspace = true

[dev-dependencies]
futures-concurrency.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true